language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
env:
    - "RECURLY_API=somekey"
    - "RECURLY_PUBLIC=somekey"
    - "SUBDOMAIN=example.com"
script: python manage.py test
